controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\StartForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\HttpException;
use app\models\QuestionForm;
use app\models\ResultForm;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['start-test', 'answer', 'start-test-again'],
                'rules' => [
                    [
                        'actions' => ['start-test'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['answer'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['start-test-again'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['get'],
                    'start-test' => ['post'],
                    'answer' => ['post'],
                    'start-test-again' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            /*'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],*/
        ];
    }

    /**
     * Выдаем стартовую форму или соотв.данные при перезагрузке страницы
     * @return string
     */
    public function actionIndex()
    {
        // Если перезагрузка страницы - показываем вопрос или результат теста
        if (!Yii::$app->user->isGuest) {

            // в зависимости от стадии теста выдаем следующий вопрос или результат

            // тест окончен
            if (\Yii::$app->SkyengService->testIsFinished) {
                // получаем результат
                $ResultForm = \Yii::$app->SkyengService->getResult();

                return $this->render('result', [
                    'ResultForm' => $ResultForm
                ]);
            }

            // тест продолжается

            // получаем вопрос, повторяем, а не задаем новый
            $QuestionForm = \Yii::$app->SkyengService->getQuestion(true);

            return $this->render('question', [
                'QuestionForm' => $QuestionForm
            ]);
        }

        // Иначе показываем стартовую форму
        $StartForm = new StartForm();

        return $this->render('index', [
            'StartForm' => $StartForm
        ]);

    }

    /**
     * Регистрируем юзера и задаем первый вопрос.
     * @return string
     * @throws HttpException
     */
    public function actionStartTest()
    {
        // валидируем имя юзера
        $StartForm = new StartForm();
        if (!$StartForm->load(Yii::$app->request->post()) || !$StartForm->validate()) {
            throw new HttpException(500, \Yii::t('app', 'Sorry, there are some problems'));
        }

        // регистрируем юзера
        \Yii::$app->SkyengService->registerUser($StartForm);

        // получаем первый вопрос
        $QuestionForm = \Yii::$app->SkyengService->getQuestion();

        return $this->renderAjax('question', [
            'QuestionForm' => $QuestionForm
        ]);
    }

    /**
     * Проверяем ответ юзера и выдаем новый вопрос или результат теста
     * @return string
     * @throws HttpException
     */
    public function actionAnswer()
    {
        // валидируем ответ юзера
        $QuestionForm = new QuestionForm();
        if (!$QuestionForm->load(Yii::$app->request->post()) || !$QuestionForm->validate()) {
            throw new HttpException(500, \Yii::t('app', 'Sorry, there are some problems'));
        }

        // обрабатываем ответ юзера
        \Yii::$app->SkyengService->handleAnswer($QuestionForm);

        // в зависимости от стадии теста выдаем следующий вопрос или результат

        // тест окончен
        if (\Yii::$app->SkyengService->testIsFinished) {
            // получаем результат
            $ResultForm = \Yii::$app->SkyengService->getResult();

            return $this->renderAjax('result', [
                'ResultForm' => $ResultForm
            ]);
        }

        // тест продолжается

        // получаем вопрос
        $QuestionForm = \Yii::$app->SkyengService->getQuestion();

        return $this->renderAjax('question', [
            'QuestionForm' => $QuestionForm
        ]);
    }

    /**
     * Разлогиниваем юзера и показываем стартовую страницу
     * @return string
     */
    public function actionStartTestAgain()
    {
        // разлогиниваем юзера
        \Yii::$app->SkyengService->logoutUser();

        $StartForm = new StartForm();

        return $this->renderAjax('index', [
            'StartForm' => $StartForm
        ]);
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $StartForm app\models\StartForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\SkyengService;

$this->title = 'My Yii Application';

/*$js = <<<'EOD'

var $form   = $('#start-form'),
    action  = $form.attr("action"),
    data    = $form.serialize();



    $form.on('beforeSubmit', function () {
        $.post(action, data)
            .done(function() {
                alert( "success" );
            })
            .fail(function() {
                alert( "error" );
            })
            .always(function() {
                alert( "finished" );
            });
        return false;
    });

EOD;

$this->registerJs($js);*/
?>

<section id="container">

    <?php $Form = ActiveForm::begin([
        'id' => 'form',
        'action' => Url::to(['site/start-test']),
        'options' => ['class' => 'form-horizontal'],
    ]); ?>

    <h3 class="form-text"><?= Html::encode(Yii::t('app', 'Enter name')) ?></h3>

    <?= $Form->field($StartForm, 'name')->textInput(['autofocus' => true, 'maxlength' => 255])->label(false) ?>

    <?= Html::button(Yii::t('app', 'Start test'), ['class' => 'btn btn-primary center-block submitter']) ?>

    <?php ActiveForm::end(); ?>

</section>

views/site/question.php
<?php

/* @var $this yii\web\View */
/* @var $QuestionForm QuestionForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\SkyengService;
use app\models\QuestionForm;

$this->title = 'My Yii Application';

?>

<section id="container">

    <?php $Form = ActiveForm::begin([
        'id' => 'form',
        'action' => Url::to(['site/answer']),
    ]); ?>

    <?php if ($QuestionForm->errorMessage): ?>
    <div class="alert alert-danger">
        <?= Html::encode($QuestionForm->errorMessage) ?>
    </div>
    <?php endif; ?>

    <h3 class="form-text"><?= Html::encode($QuestionForm->name).', ' ?><span class="label label-default"><?= Html::encode($QuestionForm->word) ?></span><?= Html::encode(' - '.Yii::t('app', 'is')) ?></h3>

    <div class="panel panel-default">
        <div class="panel-body">
            <?= $Form->field($QuestionForm, 'answer')->radioList($QuestionForm->options)->label(false) ?>
        </div>
    </div>

    <?= Html::button(Yii::t('app', 'To answer'), ['class' => 'btn btn-primary center-block submitter']) ?>

    <?php ActiveForm::end(); ?>

</section>

views/site/result.php
<?php

/* @var $this yii\web\View */
/* @var $ResultForm ResultForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\SkyengService;
use app\models\ResultForm;

$this->title = 'My Yii Application';

?>

<section id="container">

    <?php $Form = ActiveForm::begin([
        'id' => 'form',
        'action' => Url::to(['site/start-test-again']),
    ]); ?>

    <h3 class="form-text">
        <?= Html::encode(
            $ResultForm->name.', '.Yii::t('app', 'You have got')
            .' '.Yii::t('app', '{n, plural, =0{0 points} =1{1 point} other{# points}}', ['n' => $ResultForm->score])
            .' '.Yii::t('app', 'and made').' '.Yii::t('app', '{n, plural, =0{0 mistakes} =1{1 mistake} other{# mistakes}}', ['n' => $ResultForm->mistakes]).'.'
        ) ?>
    </h3>

    <?= Html::button(Yii::t('app', 'Start test again'), ['class' => 'btn btn-primary center-block submitter']) ?>

    <?php ActiveForm::end(); ?>

</section>